-- BORRADO DE TABLAS

DROP TABLE IF EXISTS EMPLEADOS;
DROP TABLE IF EXISTS DEPARTAMENTOS;
DROP TABLE IF EXISTS VENTAS;

-- CREAR TABLA EMPLEADOS
CREATE TABLE EMPLEADOS (
  ID_EMPLEADO INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE VARCHAR(50),
  EDAD INT,
  SALARIO DECIMAL(10, 2),
  ID_DEPARTAMENTO INTEGER,
  FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO)
);
-- CREAR TABLA DEPARTAMENTOS
CREATE TABLE DEPARTAMENTOS (
  ID_DEPARTAMENTO INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE_DEPARTAMENTO VARCHAR(50)
);
-- CREAR TABLA VENTAS
CREATE TABLE VENTAS (
  ID_VENTA INTEGER PRIMARY KEY AUTOINCREMENT,
  FECHA_VENTA DATE,
  MONTO DECIMAL(10, 2),
  ID_EMPLEADO INTEGER,
  FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);
-- INSERTAR REGISTROS EN LA TABLA DE EMPLEADOS

INSERT INTO EMPLEADOS (NOMBRE, EDAD, SALARIO, ID_DEPARTAMENTO) VALUES ('JESUS', 33, 5000000, 1000);
INSERT INTO EMPLEADOS (NOMBRE, EDAD, SALARIO, ID_DEPARTAMENTO) VALUES ('PEDRO', 50, 3500000, 1001);
INSERT INTO EMPLEADOS (NOMBRE, EDAD, SALARIO, ID_DEPARTAMENTO) VALUES ('SANTIAGO', 19, 1895300, 1003);
INSERT INTO EMPLEADOS (NOMBRE, EDAD, SALARIO, ID_DEPARTAMENTO) VALUES ('JUAN', 25, 1300000, 1003);
INSERT INTO EMPLEADOS (NOMBRE, EDAD, SALARIO, ID_DEPARTAMENTO) VALUES ('JUDAS', 25, 935000, 1003);

-- INSERTAR REGISTROS EN LA TABLA DE DEPARTAMENTOS

INSERT INTO DEPARTAMENTOS (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO) VALUES (1000,'GERENCIA');
INSERT INTO DEPARTAMENTOS (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO) VALUES (1001,'SUBGERENCIA');
INSERT INTO DEPARTAMENTOS (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO) VALUES (1002,'LOGISTICA');
INSERT INTO DEPARTAMENTOS (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO) VALUES (1003,'VENTAS');

-- INSERTAR REGISTROS EN LA TABLA DE VENTAS

INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (001,01/10/2024,350000,3);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (002,01/10/2024,125000,3);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (003,02/10/2024,589400,4);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (004,02/10/2024,723000,4);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (005,03/10/2024,634560,4);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (006,03/10/2024,299250,3);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (007,03/10/2024,862030,5);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (008,04/10/2024,1368000,5);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (009,05/10/2024,600720,5);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (010,05/10/2024,1790800,5);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (011,05/10/2024,3690433,5);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA,MONTO,ID_EMPLEADO) VALUES (012,05/10/2024,467000,5);

-- CONSULTAS VARIAS 

-- TOTAL VENTAS REALIZADA POR LOS EMPLEADOSDEPARTAMENTOS
SELECT SUM(MONTO) AS TOTAL_VENTAS FROM VENTAS;
-- SALARIO PROMEDIO DE LOS EMPLEADOSDEPARTAMENTOS
SELECT AVG(SALARIO) AS PROMEDIO_SALARIO FROM EMPLEADOS;
-- CONSULTA DE EMPLEADOS POR DEPARTAMENTO
SELECT B.NOMBRE_DEPARTAMENTO, COUNT(A.ID_EMPLEADO) AS TOTAL_EMPLEADOS
FROM EMPLEADOS A
INNER JOIN DEPARTAMENTOS B ON A.ID_DEPARTAMENTO = B.ID_DEPARTAMENTO
GROUP BY B.ID_DEPARTAMENTO
ORDER BY B.NOMBRE_DEPARTAMENTO;
-- NOMBRE DE EMPLEADOS Y NOMBRE DEL DEPARTAMENTODEPARTAMENTOS
SELECT A.NOMBRE,B.NOMBRE_DEPARTAMENTO
FROM EMPLEADOS A
INNER JOIN DEPARTAMENTOS B
ON A.ID_DEPARTAMENTO=B.ID_DEPARTAMENTO;
-- NOMBRE DE EMPLEADOS Y NOMBRE DEL DEPARTAMENTODEPARTAMENTOS
SELECT A.NOMBRE_DEPARTAMENTO,B.NOMBRE
FROM DEPARTAMENTOS A
LEFT JOIN EMPLEADOS B
ON A.ID_DEPARTAMENTO=B.ID_DEPARTAMENTO;
-- CONSULTA FULL JOIN
SELECT EMPLEADOS.nombre, DEPARTAMENTOS.nombre_departamento 
FROM EMPLEADOS 
LEFT JOIN DEPARTAMENTOS 
ON EMPLEADOS.ID_DEPARTAMENTO = DEPARTAMENTOS.ID_DEPARTAMENTO 
UNION SELECT EMPLEADOS.NOMBRE,DEPARTAMENTOS.NOMBRE_DEPARTAMENTO 
FROM EMPLEADOS 
RIGHT JOIN DEPARTAMENTOS 
ON EMPLEADOS.ID_DEPARTAMENTO = DEPARTAMENTOS.ID_DEPARTAMENTO;

-- ACTUALIZAR SALARIO DE UN EMPLEADO 

UPDATE EMPLEADOS SET SALARIO=SALARIO * 1.35 WHERE NOMBRE='JUAN';

-- ELIMINA UN EMPLEADO QUE SU SALARIO SEA MENOR A 1.5 MILLONES

DELETE FROM EMPLEADOS WHERE SALARIO <1500000;